### ISSUE TITLE
Incompatible with Ember 4

### ISSUE THREAD

**Issue by dfreeman** [ember-truncate/ember-truncate#472]
I'm not sure how actively maintained this addon is, but it looks like its templates rely on the deprecated (and now removed) [implicit-`this` fallback](https://deprecations.emberjs.com/v3.x/#toc_this-property-fallback). When used with `ember-source@^4`, I see an error like this:

```
Error: Attempted to resolve a value in a strict mode template, but that value was not in scope: _truncate
```

**Comment by scalvert** [comment]
Hey Dan, it's only sporadically maintained. It's likely we can resolve this issue though, and should likely update the blueprint to ensure we're testing for all the latest version variants.

**Comment by dfreeman** [comment]
Thanks, Steve! I can open a PR or two to try and get things up to date, I just wanted to make sure that wouldn't be time better spent looking into an alternative library 🙂
