### ISSUE TITLE
Could you grant me Admin with publish rights to NPM?

### ISSUE THREAD

**Issue by scalvert** [ember-truncate/ember-truncate#65]
@nickiaconis, I've been working on merging a bunch of PRs for this repo, but do not have Admin, so cannot subsequently setup CI. I also cannot publish to NPM, so cannot release new versions. Can you give me permissions?

**Comment by scalvert** [comment]
cc: @mhluska

**Comment by scalvert** [comment]
@nickiaconis ping

**Comment by nickiaconis** [comment]
whoops! sorry about that and about the delay @scalvert! I've set you to the owner role on the GitHub org. I've also added you as a maintainer on NPM. hopefully that solves all the issues. 😬
